'use strict';
const menuButton = document.querySelector('.menu-toggle');
const navigation = document.querySelector('#navigation');
function closeMenu() { navigation.classList.remove('open'); menuButton.setAttribute('aria-expanded', 'false'); }
menuButton.addEventListener('click', () => { const isOpen = navigation.classList.toggle('open'); menuButton.setAttribute('aria-expanded', String(isOpen)); });
navigation.querySelectorAll('a').forEach(link => link.addEventListener('click', closeMenu));
document.addEventListener('keydown', event => { if (event.key === 'Escape') closeMenu(); });
window.matchMedia('(min-width: 761px)').addEventListener('change', event => { if (event.matches) closeMenu(); });
document.querySelector('#year').textContent = new Date().getFullYear();
const cases = {
  boxtwin: `<p class="eyebrow">CASE / HYDROGENI</p><h2 id="case-title">BoxTwin 3D</h2><p>Um protótipo que conecta medição, visualização e operação portuária.</p><div class="case-block"><h3>O problema</h3><p>Acompanhar o volume de fertilizantes em boxes com menor dependência de estimativas visuais e contagens manuais.</p></div><div class="case-block"><h3>A solução desenvolvida pela equipe</h3><p>Um gêmeo digital 3D com representação dos boxes, informações de volume e ocupação, histórico e alertas. A arquitetura proposta conecta leituras de sensores ao monitoramento operacional.</p></div><div class="case-block"><h3>Minha participação</h3><p>Contribuí com a criação do nome HydrogenI, participei da visita técnica para conhecer o contexto da operação e apoiei o trabalho de IoT e engenharia na concepção da solução.</p></div><div class="case-block"><h3>Tecnologias e conceitos</h3><div class="tags"><span>JavaScript</span><span>Gêmeo digital</span><span>Visualização 3D</span><span>Sensores ToF</span><span>IoT</span></div></div><div class="case-result"><h3>Resultado</h3><p>Equipe vencedora do Hackathon do Complexo Portuário do Itaqui 2026, com uma próxima etapa de aceleração para desenvolver, testar e validar o protótipo.</p></div><a class="button primary" href="https://hydrogeni-boxtwin-production.up.railway.app/simulador" target="_blank" rel="noopener noreferrer">Abrir demonstração</a><p class="case-footnote">A demonstração apresenta o MVP. A integração e validação em campo fazem parte da evolução do projeto.</p>`,
  baja: `<p class="eyebrow">PROJETO / ENGENHARIA</p><h2 id="case-title">Baja SAE — Ceuma</h2><p>Software e eletrônica explorados no contexto de um veículo off-road.</p><div class="case-block"><h3>O objetivo</h3><p>Organizar e apresentar o funcionamento de um projeto conceitual de veículo Baja SAE, conectando engenharia mecânica, eletrônica e visualização digital.</p></div><div class="case-block"><h3>A experiência</h3><p>O site reúne um protótipo 3D interativo, uma proposta de eletrônica embarcada com ESP32-S3, telemetria simulada e informações sobre os sistemas do veículo e regras da competição.</p></div><div class="case-block"><h3>Tecnologias e conceitos</h3><div class="tags"><span>ESP32-S3</span><span>Telemetria simulada</span><span>Visualização 3D</span><span>Engenharia mecânica</span></div></div><div class="case-result"><p>Projeto conceitual para estudo e exploração. A telemetria apresentada é simulada.</p></div><a class="button primary" href="https://geovannehh.github.io/BAJA-SAE-CEUMA/" target="_blank" rel="noopener noreferrer">Explorar projeto</a>`
};
const dialog = document.querySelector('#case-dialog');
let returnFocus;
document.querySelectorAll('[data-case]').forEach(button => button.addEventListener('click', () => { returnFocus = button; document.querySelector('#case-content').innerHTML = cases[button.dataset.case]; dialog.showModal(); document.body.classList.add('dialog-open'); }));
document.querySelector('.dialog-close').addEventListener('click', () => dialog.close());
dialog.addEventListener('click', event => { if (event.target === dialog) { const rect = dialog.getBoundingClientRect(); if (event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom) dialog.close(); } });
dialog.addEventListener('close', () => { document.body.classList.remove('dialog-open'); returnFocus?.focus(); });
if ('IntersectionObserver' in window) { const observer = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) navigation.querySelectorAll('a').forEach(link => { const active = link.hash === '#' + entry.target.id; link.classList.toggle('active', active); if (active) link.setAttribute('aria-current', 'location'); else link.removeAttribute('aria-current'); }); }); }, {rootMargin: '-15% 0px -55% 0px'}); navigation.querySelectorAll('a').forEach(link => { const section = document.querySelector(link.hash); if (section) observer.observe(section); }); }
